In [1]:
%matplotlib inline

In [2]:
from __future__ import division
import numpy as np

In [3]:
def kmr_markov_matrix(p=1/3, N=4, epsilon=0.01):
    """
    Generate the transition probability matrix for the KMR dynamics with
    two acitons.

    """
    P = np.zeros((N+1, N+1))
    P[0,0] = 1 - epsilon
    P[0,1] = epsilon
    P[N,N] = 1 - epsilon
    P[N,N-1] = epsilon
    for n in range(1, N):
        if (n-1)/(N-1) < p:
            a1_ratio = (n-1)/(N-1)
        elif (n-1)/(N-1) == p:
            a1_ratio = (n-1)/(N-1)/2
        P[n, n-1] = (n/N) * ((epsilon/2) + (1-epsilon)*(a1_ratio))
        if (n / (N-1)) > p:
            a2_ratio = n / (N-1)
        elif n / (N-1) == p:
            a2_ratio = n / (N-1) / 2
        P[n, n+1] = ((N-n)/N) * ((epsilon/2) + ((1-epsilon) * a2_ratio))
        P[n, n] = 1 - P[n, n-1] - P[n, n+1]
    return P


In [5]:
import quantecon as qe
P =  kmr_markov_matrix()
mc = qe.MarkovChain(P)

In [6]:
mc

Markov chain with transition matrix 
P = 
[[ 0.99     0.01     0.       0.       0.     ]
 [ 0.00125  0.87125  0.1275   0.       0.     ]
 [ 0.       0.085    0.5825   0.3325   0.     ]
 [ 0.       0.       0.1275   0.62375  0.24875]
 [ 0.       0.       0.       0.01     0.99   ]]

In [7]:
mc.stationary_distributions

array([[ 0.00120375,  0.00963002,  0.01444503,  0.03767038,  0.93705081]])

In [14]:
mc.simulate(0, 10000)

array([0, 0, 0, ..., 4, 4, 4])

In [16]:
#MarkovChain クラスのメソッドを使うところまでできました。

In [15]:
import matplotlib.pyplot as plt

In [24]:
from kmr import KMR

In [3]:
p = 1/3
N = 6
epsilon = 0.1
T = 10**3

In [21]:
kmr = KMR(p, N, epsilon)

AttributeError: 'KMR' object has no attribute 'kmr_markov_matrix'

In [18]:
kmr.simulate(T)

TypeError: simulate() takes at most 3 arguments (4 given)

In [19]:
kmr.compute_stationary_distribution()

array([  4.39557521e-06,   5.27469026e-05,   6.06589379e-04,
         6.63204388e-03,   5.86935883e-02,   3.61552504e-01,
         5.72458132e-01])

In [20]:
kmr.plot_sample_path()

AttributeError: 'KMR' object has no attribute 'plot_sample_path'